


###
POST https://api.openai.com/v1/chat/completions
Content-Type: application/json
Authorization: Bearer mySecret,

{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
}
###

### skumt, funkar i postman men inte här